#!/usr/bin/env python3

# This program, when run from the command line, will watch the directory given
# as the first argument (or the current directory, if none is provided), and
# upload any new files that appear in it to AWS S3, deleting them afterwards.
#
# For the upload to work, certain environment variables must be set (see upload.py).

import sys
from upload import upload_and_delete_file
from watch import NewFileWatcher

if __name__ == "__main__":
    directory = sys.argv[1] if len(sys.argv) > 1 else '.'
    NewFileWatcher(directory, upload_and_delete_file).watch()
